### ISSUE TITLE
Max string length for callbacks

### ISSUE THREAD

**Issue by KingCodename** [udan11/samp-plugin-sql#12]
Udan11, thanks a lot for your fast sql plugin, but please increase the max string length (from 26 up to 31 characters) for threaded query callbacks. Maybe you should also document the limit to your include flie or throw back a error when the it reached.

**Comment by udan11** [comment]
Hello,

I don't remember exactly what I did back then, but I just looked through the source and it looks like there is no limit imposed by me. As far as I know, there is the 31-characters limit imposed by AMX, but I am not sure why you are mentioning 26.

**Comment by KingCodename** [comment]
Yes, your´re right, my mistake, sorry.
