### ISSUE TITLE
MariaDB 10.x support?

### ISSUE THREAD

**Issue by KingCodename** [udan11/samp-plugin-sql#13]
Does your plugin support MariaDB 10.0 and higher or only the drop-in replacement MariaDB 5.5.x?

**Comment by udan11** [comment]
The drop-in replacement works, but I am not sure about MariaDB 10.0 and higher.

**Comment by KingCodename** [comment]
Could you check it, please? And what about the upcoming versions? Do you think they will be supported by your plugin in the future?
